export const homeData = [
  {
    nickname:"축구하고싶은사람",
    title:"축구 인원 모집",
    hour:"오후 12:00",
    date:"11월 14일 (화)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:2,
    people:1,
    hashtag:"#축구 #친목 #화요일",
  },{
    nickname:"야구하고싶은사람",
    title:"야구 인원 모집",
    hour:"오후 17:00",
    date:"11월 16일 (목)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:5,
    people:2,
    hashtag:"#야구 #친목 #목요일",
  },{
    nickname:"알고리즘공부하자",
    title:"알고리즘 스터디 인원 모집",
    hour:"오후 13:00",
    date:"11월 17일 (금)",
    place:"금오공과대학교 도서관 회의실",
    time:4,
    recruit:4,
    people:2,
    hashtag:"#공부 #코딩 #알고리즘",
  },{
    nickname:"술땡긴다",
    title:"술먹을사람?",
    hour:"오후 19:00",
    date:"11월 17일 (금)",
    place:"블랙홀 상가",
    time:6,
    recruit:4,
    people:2,
    hashtag:"#술 #불금 #달리자",
  },
];

export const category = [
  "스포츠",
  "공부",
  "술",
  "게임",
  "봉사활동",
  "기타",
];