export const homeData = [
  {
    nickname:"축구하고싶은사람",
    title:"축구 인원 모집",
    hour:"12:00",
    date:"11월 14일 (화)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:2,
    people:1,
    hashtag:"#축구 #친목 #화요일",
  },{
    nickname:"축구하고싶은사람",
    title:"축구 인원 모집",
    hour:"12:00",
    date:"11월 14일 (화)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:2,
    people:1,
    hashtag:"#축구 #친목 #화요일",
  },{
    nickname:"축구하고싶은사람",
    title:"축구 인원 모집",
    hour:"12:00",
    date:"11월 14일 (화)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:2,
    people:1,
    hashtag:"#축구 #친목 #화요일",
  },{
    nickname:"축구하고싶은사람",
    title:"축구 인원 모집",
    hour:"12:00",
    date:"11월 14일 (화)",
    place:"금오공과대학교 대운동장",
    time:2,
    recruit:2,
    people:1,
    hashtag:"#축구 #친목 #화요일",
  },
]